# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "trusty64"
  config.vm.box_url = "https://cloud-images.ubuntu.com/vagrant/trusty/current/trusty-server-cloudimg-amd64-vagrant-disk1.box"

config.vm.provider "virtualbox" do |v|
    v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    v.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
end

  config.vm.network :forwarded_port, guest: 3050, host: 3050, auto_correct: true
  config.vm.network :private_network, ip: "192.168.80.10"
  config.ssh.forward_agent = true
  config.vm.synced_folder "." , "/home/cloud-db"
  config.vm.provision 'shell', inline: 'cd /opt;sudo rm -rf /opt/cloud-init;sudo mkdir /opt/cloud-init;sudo chmod 777 /opt/cloud-init/;cd /opt/cloud-init; sudo wget https://raw.githubusercontent.com/Superlogica/framework/master/vagrant/cloud-init-init --no-check-certificate; sudo chmod 777 /opt/cloud-init/cloud-init-init; sudo /opt/cloud-init/cloud-init-init fb25;'





end
