approve_by_comment: true
approve_regex: ^Approved
reject_regex: ^Rejected
reset_on_push: false
reviewers:
    -
        name: infra
        required: 1
        members:
            - carlossuperlogica
            - luiscera
            - rafael-sbrissa
            - leandropanhan
            - jhoncf
        
