# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "lucid64"
  config.vm.box_url = "http://files.vagrantup.com/lucid64.box"


	config.vm.provider "virtualbox" do |v|
		v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
		v.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
	end

  config.vm.network :forwarded_port, guest: 80, host: 3059, auto_correct: true
  config.vm.network :forwarded_port, guest: 3050, host: 3050, auto_correct: true
  config.vm.network :private_network, ip: "192.168.80.10"
  config.ssh.forward_agent = true
  config.vm.synced_folder "./db", "/home/cloud-db"
  config.vm.synced_folder ".", "/home/cloud", type: "rsync", rsync__exclude: [".git/","fb/", "var/","utils/", "db/"], id: "home-cloud"
  config.vm.provision 'shell', inline: 'cd /tmp; sudo rm /tmp/cloud-init-init; sudo wget https://raw.githubusercontent.com/Superlogica/framework/master/vagrant/cloud-init-init --no-check-certificate; sudo chmod 777 /tmp/cloud-init-init; sudo /tmp/cloud-init-init cloudteste;'
end