#!/bin/bash

#############################################################
#execute.sh                                                 #
#                                                           #
#USO: Executa comandos de rotinas da infra                  #
#                                                           #
#EXEMPLO: sudo execute masterdeploy                         #
#                                                           #
#AUTOR: Jean Rodrigues 17/08/2016                           #
#                                                           #
#OBS: Lista de comandos no fim do arquivo                   #
#                                                           #
#                                                           #
#      V.2.0 BETA 18.08.16                                  #
#                                                           #
#-Correções de bugs                                         #
#-Adicionado a opção deploy no subadquirente                #
#                                                           #
#                                                           #
#                                                           #
#############################################################

#[SERVIDORES]

firebirdtrial1963="ec2-54-94-57-179.sa-east-1.compute.amazonaws.com"

admin1967="ec2-54-207-255-100.sa-east-1.compute.amazonaws.com"

firebirdtrial4079="ec2-54-94-56-182.sa-east-1.compute.amazonaws.com"

estagio="ec2-54-94-7-35.sa-east-1.compute.amazonaws.com"

appsmaster="ec2-54-207-181-24.sa-east-1.compute.amazonaws.com"

subadquirentemaster="52.67.95.176"

subadquirenteestagio="52.67.100.194"

#[DEPLOYS]

case "$1" in
	masterdeploy)

	sudo ssh -t -o 'StrictHostKeyChecking no' -o ConnectTimeout=10 root@"$admin1967" 'sudo cloud todossemesperar cloud% deploy' 1>&2
	echo -e " \033[0;32m FIM DO SCRIPT \033[0m"
	sleep 2; clear; exit 0
;;

estagiodeploy)

	sudo ssh -t -o 'StrictHostKeyChecking no' -o ConnectTimeout=10 root@$admin1967 'sudo cloud todos cloudex8735 deploy' 1>&2
	echo -e " \033[0;32m FIM DO SCRIPT \033[0m"
	sleep 2; clear; exit 0
;;

appsdeploy)

    sudo ssh -t -o 'StrictHostKeyChecking no' -o ConnectTimeout=10 root@$admin1967 'sudo cloud todossemesperar apps% deploy apps' 1>&2
    echo -e " \033[0;32m FIM DO SCRIPT \033[0m"1>&2
    sleep 2; clear; exit 0
;;
deploysubad)

	sudo ssh -t -o 'StrictHostKeyChecking no' -o ConnectTimeout=10 root@$subadquirentemaster 'sudo cloud deploy' 1>&2
	sudo ssh -t -o 'StrictHostKeyChecking no' -o ConnectTimeout=10 root@$subadquirenteestagio 'sudo cloud deploy' 1>&2
	echo -e " \033[0;32m FIM DO SCRIPT \033[0m"
	sleep 2; clear; exit 0
;;
#[SUPORTE]

suporte)

    sudo ssh -t -o 'StrictHostKeyChecking no' -o ConnectTimeout=10 root@$admin1967 '

    echo "DIGITE O NOME DA LICENÇA";
    read licenca;
    sudo cloud ativarSuporte "$licenca";' 1>&2

	echo -e " \033[0;32m FIM DO SCRIPT \033[0m"
    sleep 2; clear; exit 0
;;
#[UPLOAD]

upload)

    sudo ssh -t -o 'StrictHostKeyChecking no' -o ConnectTimeout=10 root@$firebirdtrial1963 '

    echo "DIGITE O NOME DA LICENÇA";
	read licenca;
	sudo cloud upload "$licenca";' 1>&2

    echo -e " \033[0;32m FIM DO SCRIPT \033[0m"
    sleep 2; clear; exit 0
;;
#[DOWNLOAD]

download)

    sudo ssh -t -o 'StrictHostKeyChecking no' -o ConnectTimeout=10 root@$firebirdtrial1963 ' 

    echo "DIGITE O NOME DO ARQUIVO";
	read arquivo;
	sudo cloud download "$arquivo";' 1>&2

    echo -e " \033[0;32m FIM DO SCRIPT \033[0m"
    sleep 2; clear; exit 0
;;
#[ISQL]

isql)

    sudo ssh -t -o 'StrictHostKeyChecking no' -o ConnectTimeout=10 root@$firebirdtrial1963 '

    echo "DIGITE O NOME DA LICENÇA";
	read licenca;
	sudo cloud isql "$licenca";' 1>&2

    echo -e " \033[0;32m FIM DO SCRIPT \033[0m"
    sleep 2; clear; exit 0
;;
#[MYSQL DE APPS]

uploadmysql)

    sudo ssh -t -o 'StrictHostKeyChecking no' -o ConnectTimeout=10 root@$appsmaster '

    echo "DIGITE O NOME DO APP";
	read licenca;
	sudo cloud upload "$licenca";' 1>&2

    echo -e " \033[0;32m FIM DO SCRIPT \033[0m"
    sleep 2; clear; exit 0
;;

conectarappsmaster)

    sudo ssh -t -o 'StrictHostKeyChecking no' -o ConnectTimeout=10 root@$appsmaster 1>&2
    echo -e " \033[0;32m FIM DO SCRIPT \033[0m"
    sleep 2; clear; exit 0

;;

#[MASTER SUBADQUIRENTE]

conectarsubadmaster)

    sudo ssh -t -o 'StrictHostKeyChecking no' -o ConnectTimeout=10 root@$subadquirentemaster 1>&2
    echo -e " \033[0;32m FIM DO SCRIPT \033[0m"
    sleep 2; clear; exit 0

;;
#INFRA

novaestagio)

    sudo ssh -t -o 'StrictHostKeyChecking no' -o ConnectTimeout=10 root@$estagio '

	cd /home/cloud/;
	sudo cloud deploy;
 	echo "DIGITE O NOVO NOME DA ESTÁGIO";
    read nome_estagio;
    sudo git checkout "$nome_estagio";
    sudo cloud deploy;
    git status;' 1>&2

	echo -e " \033[0;32m FIM DO SCRIPT \033[0m"
	sleep 2; clear; exit 0
;;
#[COMANDOS - AJUDA]
-help)
	
	echo -e " \033[0;34m AJUDA - USE: sudo execute comando \033[0m"
    echo ""
	echo -e " \033[0;33m masterdeploy [EXECUTA DEPLOY NO SERVIDOR MASTER E ESTAGIO] \033[0m"
	echo ""
	echo -e " \033[0;33m estagiodeploy [EXECUTA DEPLOY NO SERVIDOR ESTAGIO] \033[0m"
	echo ""
	echo -e " \033[0;33m appsdeploy [EXECUTA DEPLOY NO SERVIDOR APPS] \033[0m"
	echo ""
	echo -e " \033[0;33m deploysubad [EXECUTA DEPLOY NO SERVIDOR MASTER SUBADQUIRENTE] \033[0m"
	echo ""
	echo -e " \033[0;33m suporte [LIBERA USUARIO SUPORTE] \033[0m"
	echo ""
	echo -e " \033[0;33m upload [BAIXA BASES FIREBIRD  E SALVA O ARQUIVO EM (SLNAS) //192.168.0.40/home/temp...]\033[0m" " \033[0;31m   [USE COM SABEDORIA] \033[0m"
    echo ""
#   echo -e " \033[0;33m download [DOWNLOAD - ENVIA ARQUIVOS - PARA O FIREBIRDTRIAL1963 E SALVA O ARQUIVO EM /home/ubuntu/downloads] \033[0m"
#   echo ""
    echo -e " \033[0;33m isql [EXECUTA SELECT, UPDATE, INSERT NO FIREBIRD] \033[0m" " \033[0;31m   [USE COM MUITA SABEDORIA] \033[0m"
	echo ""
	echo -e " \033[0;33m uploadmysql [BAIXA BASES MYSQL DE APPS] \033[0m"
	echo ""
	echo -e " \033[0;33m conectarappsmaster [CONECTA NO SERVIODR MYSQL DE APPS] \033[0m"
	echo ""
	echo -e " \033[0;33m -h [EXIBE TODOS OS COMANDOS E SUAS FUNCIONALIDADES] \033[0m"
	exit 1
;;
#[MENSAGEM OPÇÃO INVÁLIDA]
*)
	echo -e " \033[0;32m OPÇÃO INVÁLIDA \033[0m"
	sleep 2; clear; exit 0
;;
esac
done