#!/bin/bash

#[SERVIDORES]

firebirdtrial1963=""

admin1967=""

firebirdtrial4079=""

estagio=""

appsmaster=""

appsmaster2=""

appsestagio=""

subadquirentemaster=""

subadquirenteestagio=""

#[USUARIOS]
usuario=""


#[DEPLOYS] [INFRA, DEVS E DEV-ADMIN]

case "$1" in
	masterdeploy)

	sudo -u $usuario ssh -t -o 'StrictHostKeyChecking no' -o ConnectTimeout=10 $usuario@$admin1967 'sudo cloud todossemesperar cloud% deploy' 1>&2
	echo -e " \033[0;32m FIM DO SCRIPT \033[0m"
	sleep 2; clear; exit 0
;;

estagiodeploy)

	sudo -u $usuario ssh -t -o 'StrictHostKeyChecking no' -o ConnectTimeout=10 $usuario@$admin1967 'sudo cloud todos cloudex8735 deploy' 1>&2
	sudo -u $usuario ssh -t -o 'StrictHostKeyChecking no' -o ConnectTimeout=10 $usuario@$admin1967 'sudo cloud todos cloudex10717 deploy' 1>&2
    echo -e " \033[0;32m FIM DO SCRIPT \033[0m"
	sleep 2; clear; exit 0
;;

appsdeploy)

    sudo -u $usuario ssh -t -o 'StrictHostKeyChecking no' -o ConnectTimeout=10 $usuario@$admin1967 'sudo cloud todossemesperar apps% deploy apps' 1>&2
    echo -e " \033[0;32m FIM DO SCRIPT \033[0m"1>&2
    sleep 2; clear; exit 0
;;
deploysubad)

	sudo -u $usuario ssh -t -o 'StrictHostKeyChecking no' -o ConnectTimeout=10 $usuario@$subadquirentemaster 'sudo cloud deploy' 1>&2
	echo -e " \033[0;32m FIM DO SCRIPT \033[0m"
	sleep 2; clear; exit 0

;;
deploysubadestagio)

    sudo -u $usuario ssh -t -o 'StrictHostKeyChecking no' -o ConnectTimeout=10 $usuario@$subadquirenteestagio 'sudo cloud deploy' 1>&2
    echo -e " \033[0;32m FIM DO SCRIPT \033[0m"
    sleep 2; clear; exit 0

;;
#[SUPORTE] [INFRA E TODOS ADMIN]

suporte)

    sudo -u $usuario ssh -t -o 'StrictHostKeyChecking no' -o ConnectTimeout=10 $usuario@$admin1967 '

    echo "DIGITE O NOME DA LICENÇA";
    read licenca;
    sudo cloud ativarSuporte "$licenca";' 1>&2

	echo -e " \033[0;32m FIM DO SCRIPT \033[0m"
    sleep 2; clear; exit 0
;;
#[UPLOAD] [INFRA E DEV-ADMIN]

upload)

    sudo -u $usuario ssh -t -o 'StrictHostKeyChecking no' -o ConnectTimeout=10 $usuario@$firebirdtrial1963 '

    echo "DIGITE O NOME DA LICENÇA";
	read licenca;
	sudo cloud upload "$licenca";' 1>&2

    echo -e " \033[0;32m FIM DO SCRIPT \033[0m"
    sleep 2; clear; exit 0
;;

#[ISQL] [INFRA E DEV-ADMIN]

isql)

    sudo -u $usuario ssh -t -o 'StrictHostKeyChecking no' -o ConnectTimeout=10 $usuario@$firebirdtrial1963 '

    echo "DIGITE O NOME DA LICENÇA";
	read licenca;
	sudo cloud isql "$licenca";' 1>&2

    echo -e " \033[0;32m FIM DO SCRIPT \033[0m"
    sleep 2; clear; exit 0
;;
#[MYSQL DE APPS] [INFRA E DEV-ADMIN]

uploadmysql)

    sudo -u $usuario ssh -t -o 'StrictHostKeyChecking no' -o ConnectTimeout=10 $usuario@$appsmaster '

    echo "DIGITE O NOME DO APP";
	read licenca;
	sudo cloud upload "$licenca";' 1>&2

    echo -e " \033[0;32m FIM DO SCRIPT \033[0m"
    sleep 2; clear; exit 0
;;
#INFRA [INFRA E DEV-ADMIN]

novaestagio)

    sudo -u $usuario ssh -t -o 'StrictHostKeyChecking no' -o ConnectTimeout=10 $usuario@$estagio '

	cd /home/cloud/;
	sudo cloud deploy;
 	echo "DIGITE O NOVO NOME DA ESTÁGIO";
    read nome_estagio;
    sudo git checkout "$nome_estagio";
    sudo cloud deploy;
    git status;' 1>&2

	echo -e " \033[0;32m FIM DO SCRIPT \033[0m"
	sleep 2; clear; exit 0

;;

conectaradmin)

    sudo -u $USER ssh -t -o 'StrictHostKeyChecking no' -o ConnectTimeout=10 $USER@$admin1967 1>&2
    echo -e " \033[0;32m FIM DO SCRIPT \033[0m"
    sleep 2; clear; exit 0
;;

conectarappsmaster)

    sudo -u $USER ssh -t -o 'StrictHostKeyChecking no' -o ConnectTimeout=10 $USER@$appsmaster 1>&2
    echo -e " \033[0;32m FIM DO SCRIPT \033[0m"
    sleep 2; clear; exit 0
;;

conectarappsmaster2)

    sudo -u $USER ssh -t -o 'StrictHostKeyChecking no' -o ConnectTimeout=10 $USER@$appsmaster2 1>&2
    echo -e " \033[0;32m FIM DO SCRIPT \033[0m"
    sleep 2; clear; exit 0
;;

conectarappsestagio)

    sudo -u $USER ssh -t -o 'StrictHostKeyChecking no' -o ConnectTimeout=10 $USER@$appsestagio 1>&2
    echo -e " \033[0;32m FIM DO SCRIPT \033[0m"
    sleep 2; clear; exit 0
;;

conectarsubadmaster)

    sudo -u $USER ssh -t -o 'StrictHostKeyChecking no' -o ConnectTimeout=10 $USER@$subadquirentemaster 1>&2
    echo -e " \033[0;32m FIM DO SCRIPT \033[0m"
    sleep 2; clear; exit 0
;;

reiniciarfirebird)
    SERVIDOR=$2
    if [[ ! $SERVIDOR ]]; then
        echo "Informe a label de um servidor";
        exit 0;
    fi 
    sudo -u $usuario ssh -t -o 'StrictHostKeyChecking no' -o ConnectTimeout=10 $usuario@$admin1967 'sudo cloud todos $SERVIDOR firebirdrestart' 1>&2
    echo -e " \033[0;32m FIM DO SCRIPT \033[0m"
    sleep 2; clear; exit 0
;;

#[COMANDOS AJUDA][TODOS]
-help)
	
	
echo -e " \033[0;32m
#	               LISTA DE COMANDOS
#	
#	masterdeploy [EXECUTA DEPLOY NO SERVIDOR MASTER, PILOTO E ESTAGIO]
#
#	estagiodeploy [EXECUTA DEPLOY NO SERVIDOR ESTAGIO]
#
#	appsdeploy [EXECUTA DEPLOY NO SERVIDOR APPS MASTER E ESTAGIO]
#
#	deploysubad [EXECUTA DEPLOY NO SERVIDOR MASTER DO SUBADQUIRENTE]
#
#   deploysubadestagio [EXECUTA DEPLOY NO SERVIDOR ESTAGIO DO SUBADQUIRENTE]
#
#	suporte [LIBERA USUARIO SUPORTE]
#
#	upload [BAIXA BASES FIREBIRD  E SALVA O ARQUIVO EM (SLNAS) //192.168.0.40/temp...][USE COM SABEDORIA]
#   
#   isql [EXECUTA SELECT, UPDATE, INSERT NO FIREBIRD] [USE COM MUITA SABEDORIA]
#	
#	uploadmysql [BAIXA BASES MYSQL DE APPS]
#	
#	conectarappsmaster [CONECTA NO SERVIODR MASTER MYSQL DE APPS]
#	
#	conectarappsestagio [CONECTA NO SERVIODR ESTAGIO DO MYSQL DE APPS]
#	
#	conectarsubadmaster [CONECTA NO SERVIODR MASTER DO SUBADQUIRENTE]
#	
#	conectaradmin [CONECTA NO SERVIODR ADMIN1967]
#	
#	-help [EXIBE TODOS OS COMANDOS E SUAS FUNCIONALIDADES]
#\033[0m"
	exit 1
;;
#[MENSAGEM OPÇÃO INVÁLIDA]
*)
	echo -e " \033[0;32m OPÇÃO INVÁLIDA \033[0m"
	sleep 2; clear; exit 0
;;
esac
done
