#!/bin/sh

#exclui arquivos antigos (com mais de dois dias).
find /samba/temp/* -mtime +2 -exec rm -Rf {} \;
find /samba/uploads/* -mtime +3 -exec rm -Rf {} \;
find /samba/chaves/* -mtime +3 -exec rm -Rf {} \;