#!/bin/sh

# Permissões para todos
chmod -R 777 /home/temp -R;
chmod -R +x /home/configs/scripts/*;

chgrp -R usuarios /home/programas;
chgrp -R usuarios /home/temp;
chgrp -R usuarios /home/temp/uploads;
chgrp -R usuarios /home/chaves;

#departamentos chmod
chmod -R 777 /home/configs;
chmod -R 777 /home/configs/scripts;
chmod -R 777 /home/infra;
chmod -R 777 /home/temp;
chmod -R 777 /home/temp/uploads;
chmod -R 777 /home/chaves;
chmod -R 777 /home/programas;

#departamentos grupos
chgrp -R infra /home/infra;


#exclui arquivos antigos (com mais de dois dias).
find /home/temp/* -mtime +2 -exec rm -Rf {} \;
find /home/temp/uploads/* -mtime +3 -exec rm -Rf {} \;
find /home/chaves/* -mtime +3 -exec rm -Rf {} \;
