#!/usr/bin/php
<?php

// checa se root
if (posix_getuid() != 0) {
    echo("\nSó o root pode fazer isto. Use sudo.\n\n");
    exit(3);
}

// torna este script executável em qq diretório
if (!is_file('/usr/sbin/cloud-init')) {
    @exec("sudo ln -s ".__FILE__." /usr/sbin");
}

//parametros
$args = $GLOBALS['argv'];
$cookbook = $args[1];
array_shift($args);
array_shift($args);
if (!$cookbook){
    echo("\nNão informou cookbook a ser executado.\n\n");
    exit(3);
}

//cria diretorios
if (!is_dir("/opt/cloud-init/cloud/libs")){
  if (!mkdir("/opt/cloud-init/cloud/libs", 0777, true)) {
      die('Falhou ao criar pastas.');
  }
}

//lib
if (is_file("/opt/cloud-init/cloud/libs/lib.php")){
   @unlink("/opt/cloud-init/cloud/libs/lib.php");
}
exec("cd /opt/cloud-init/cloud/libs; sudo wget https://raw.githubusercontent.com/Superlogica/framework/master/vagrant/libs/lib.php --no-check-certificate;"); 
require_once "/opt/cloud-init/cloud/libs/lib.php";

//executa
if (is_file("/opt/cloud-init/cloud/$cookbook.php")){
   @unlink("/opt/cloud-init/cloud/$cookbook.php");
}
exec_script("cd /opt/cloud-init/cloud/; sudo wget https://raw.githubusercontent.com/Superlogica/framework/master/vagrant/cookbooks/$cookbook.php --no-check-certificate;"); 
if (!is_file("/opt/cloud-init/cloud/$cookbook.php")){
    echo("\nCookbook '$cookbook' não encontrado.\n\n");
    exit(3);
}
require "/opt/cloud-init/cloud/$cookbook.php";
call_user_func_array($cookbook."_init", $args);
