<?php
//Resultado da função indexAction que está dentro do actionController
$response = Superlogica_Response::getResponse();

//instância grid do php, localizado na pasta Grids. Passar array com conteudo desejado
$grid = new Grids_Index($response['data']);

//instância form escrito em php, localizado na pasta Forms.
$formNovoFornecedor = new Forms_Fornecedores_Put();

//Titulo da página
$this->assign('titulo', 'Fornecedores');
?>

<div id="barraDeFerramentas">
    <!--Formulário padrão de busca-->
    <?php echo $this->render('busca.phtml'); ?>
    
    <!--comportamentos tem funções escritas em um arquivo js padrão da superlogica,para adicionar novas funções editar o arquivo localizado em ../views/scripts/js/-->
    <a href="javascript:void(0);" 
       class="destaque" 
       comportamentos="cliqueAlteraVisibilidade Form.formExibir"  
       divid="<?= $formNovoFornecedor->getAttrib('id') ?>Div" >Novo</a>
    
    <div id="<?= $formNovoFornecedor->getAttrib('id') ?>Div" class="blocoEscondido">
        <?php echo $formNovoFornecedor; ?>
    </div>             
</div>

<div>
    <!--imprime a instância do grid na tela-->
    <?php echo $grid; ?>
</div>