# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "trusty"
  config.vm.box_url = "https://cloud-images.ubuntu.com/vagrant/trusty/current/trusty-server-cloudimg-amd64-vagrant-disk1.box"
  
  config.vm.network :forwarded_port, guest: 80, host: 8080, auto_correct: true  
  config.vm.network :forwarded_port, guest: 3049, host: 3049, auto_correct: true  
  config.vm.network :forwarded_port, guest: 3058, host: 3058, auto_correct: true   
  
  config.vm.network :private_network, ip: "192.168.80.10"
  
  config.ssh.forward_agent = true

  
