#!/bin/bash
versao_ubuntu_php7="16.04"
versao_ubuntu=`lsb_release -sr`
sudo apt-get update;
if [ "$versao_ubuntu_php7" == "$versao_ubuntu" ]; then
  sudo apt-get -y -q install php7.0-cli php7.0-dev php7.0-mcrypt php7.0-curl php7.0-gd php7.0-interbase php7.0-soap;
else if [ "$versao_ubuntu" == "18.04" ]; then
    sudo apt-get -y -q install php7.0-cli php7.0-dev php7.0-mcrypt php7.0-curl php7.0-gd php7.0-interbase php7.0-soap;
else
  sudo apt-get -y -q install php5-cli php5-dev php5-mcrypt php5-curl php5-gd;
fi

sudo apt-get -y -q install git-core;
sudo rm /opt/cloud-init/cloud-init;
sudo rm -Rf /opt/cloud-init/cloud;
sudo mkdir /opt/cloud-init;
sudo mkdir /opt/cloud-init/cloud;
sudo chmod 777 /opt/cloud-init/cloud;
cd /opt/cloud-init/cloud; 
sudo wget https://raw.githubusercontent.com/Superlogica/framework/master/linux/cloud-init --no-check-certificate;
sudo chmod 777 /opt/cloud-init/cloud/cloud-init;
sudo /opt/cloud-init/cloud/cloud-init $1
