# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "desenv"
  config.vm.box_url = "https://dl.dropbox.com/u/14741389/vagrantboxes/lucid64-lamp.box"
  
  config.vm.network :forwarded_port, guest: 80, host: 8080, auto_correct: true  
  config.vm.network :forwarded_port, guest: 3049, host: 3049, auto_correct: true  
  
  config.vm.network :private_network, ip: "192.168.80.10"
  
  config.ssh.forward_agent = true

  